# 数据集配置
DATASET: 'deepglobe'
DATA_DIR: 'F:/DeepGlobe'
PATCH_SIZE: 512

# 模型配置
MODEL_VERSION: 'vit_b'
IMAGE_SIZE: 1024
USE_SAM_DECODER: false
USE_LORA: true
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'

# 训练配置
BATCH_SIZE: 4
VAL_BATCH_SIZE: 4
EPOCHS: 30
BASE_LR: 0.0002
WEIGHT_DECAY: 0.01
WARMUP_EPOCHS: 5
SCHEDULER: "cosine"
MIN_LR: 1e-6
FREEZE_ENCODER: false
ENCODER_LR_FACTOR: 0.1

# 损失函数配置
ROAD_WEIGHT: 1.0
KEYPOINT_WEIGHT: 0.5
FOCAL_LOSS: false

# 推理配置
INFER_BATCH_SIZE: 64
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16
ITSC_THRESHOLD: 0.248
ROAD_THRESHOLD: 0.364
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16

# 输出配置
CHECKPOINT_DIR: "checkpoints/sam_road"
LOG_DIR: "logs/sam_road"