# 示例LoveDA数据集配置文件 - 用于首次运行

# 训练参数
TRAIN_EPOCHS: 10
TRAIN_BATCH_SIZE: 16  # 将批次大小从4降低到2以减少GPU内存使用
VAL_BATCH_SIZE: 4
NUM_WORKERS: 4
SEED: 42
ACCUMULATE_GRAD_BATCHES: 2  # 通过梯度累积模拟更大的批次大小

# 模型参数
SAM_VERSION: 'vit_b'  # 'vit_b', 'vit_l', 'vit_h'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
NO_PRETRAIN: true  # 如果预训练权重不存在，设置为true以跳过加载
PATCH_SIZE: 512  # 图像尺寸从1024降低到512以节省GPU内存
USE_SAM_DECODER: false  # 使用SAM解码器还是简单解码器
NUM_CLASSES: 8  # 包括背景类

# 优化器参数
BASE_LR: 0.001
WEIGHT_DECAY: 0.01
LR_SCHEDULER: 'cosine'  # 'cosine', 'step', 'multistep'
MIN_LR: 0.000001
LR_WARMUP: true

# 微调策略
ENCODER_LORA: true  # 使用LoRA微调编码器
LORA_RANK: 4  # LoRA秩
FREEZE_ENCODER: false  # 不使用LoRA时是否冻结编码器
ENCODER_LR_FACTOR: 0.1  # 编码器学习率系数

# 数据集参数
DATASET_ROOT: 'dataset'
REGIONS: ['Urban', 'Rural']  # 要使用的区域
SPLIT_INFO: 
  TRAIN: 'Train'
  VAL: 'Val'
  TEST: 'Test'

# 损失函数
FOCAL_LOSS: false  # 使用focal loss而不是交叉熵

# 调试选项
DEBUG: false  # 启用详细调试日志
DEBUG_SAMPLE_VIZ: false  # 可视化样本图像
BENCHMARK: false  # 性能基准测试

# 日志记录
LOG_INTERVAL: 50
SAVE_INTERVAL: 5

# 注释 - 类别映射
# 0: 背景
# 1: 建筑
# 2: 道路
# 3: 水体
# 4: 草地
# 5: 森林
# 6: 农田
# 7: 其他